apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caliper-workspace-pvc
  annotations:
  namespace: caliper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi